- name: Install nginx on Debian based OS
  become: true
  block:
  - name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Start and enable nginx service
    become_user: www-data
    service:
      name: nginx
      state: started
      enabled: yes
