---
# tasks file for joomla
- name: create dirs
  file:
    path: "/var/www/sites/joomla"
    state: directory
  
- name: insatall unzip
  apt:
    name: unzip
    state: present

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src:  https://downloads.joomla.org/cms/joomla5/5-1-4/Joomla_5-1-4-Stable-Full_Package.zip
    dest: /var/www/sites/joomla
    remote_src: yes
    
- name: Run command 
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop:
    - chown -R www-data:www-data /var/www/sites
    - chmod -R 755 /var/www/sites
