---
# tasks file for joomla
- name: create dirs
  file:
    path: "/var/www/site/joomla"
    state: directory

- name: insatall unzip
  apt:
    name: unzip
    state: present

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src:  https://downloads.joomla.org/cms/joomla5/5-2-1/Joomla_5-2-1-Stable-Full_Package.zip
    dest: /var/www/site/joomla
    remote_src: yes
