---
- name: Install mysql on Debian based OS
  become: true
  block:
  - name: Install mysql
    apt:
      name: "{{ item  }}"
      state: present
      update_cache: yes
    loop:
      - mysql-server
      - mysql-client
      - python3-pip

  - name: Start and enable mysql service
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Install pymysql
    ansible.builtin.pip:
      name: pymysql
