---
- name: Install mysql on Debian based OS
  become: true
  block:
  - name: Install mysql
    apt:
      name: "{{ item  }}"
      state: present
      update_cache: yes
    loop:
      - mysql-server
      - mysql-client
      - python3-pip

  - name: Start and enable mysql service
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Install pymysql
    ansible.builtin.pip:
      name: pymysql

  - name: set root account
    become: true
    community.mysql.mysql_user:
      name: "{{ mysql_root }}"
      password:  "{{ mysql_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      check_implicit_admin: yes

  - name: set root account
    become: true
    community.mysql.mysql_user:
      name: "{{ mysql_user }}"
      password:  "{{ mysql_user_password }}"
      check_implicit_admin: yes
      login_user: "{{ mysql_root }}"
      login_password:  "{{ mysql_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present


