---
- name: Install mysql on Debian based OS
  become: true
  block:
    - name: Install mysql
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: '{{ soft_mysql }}'

    - name: Start and enable mysql service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: true

    - name: Install pymysql
      ansible.builtin.pip:
        name: pymysql
