---
- name: Install mysql on Debian based OS
  become: true
  block:
  - name: Install mysql
    apt:
      name: mysql
      state: present
      update_cache: yes

  - name: Start and enable mysql service
    service:
      name: mysql
      state: started
      enabled: yes
# tasks file for mysql
