---
# tasks file for initapps
- name: configuration
  become: true
  block:
  - name: config nginx
    copy:
      src: /home/user/task/default.nginx
      dest: /etc/nginx/sites-available/default
  - name: Start and enable nginx service
    become_user: www-data
    service:
      name: nginx
      state: restarted
