---
# tasks file for initapps
- name: configuration
  become: true
  block:
  - name: config nginx
    copy:
      src: /home/user/task/info.php
      dest: /var/www/html/info.php
  - name: config nginx
    copy:
      src: /home/user/task/joomla.conf
      dest: /etc/nginx/sites-available/joomla.conf
  - name: symlink
    ansible.builtin.file:
      src: /etc/nginx/sites-available/joomla.conf
      dest: /etc/nginx/sites-enabled/joomla.conf
      state: link
#  - name: config nginx
#    copy:
#      src: /home/user/task/default.nginx
#      dest: /etc/nginx/sites-available/default
  - name: Start and enable nginx service
    #    become_user: www-data
    service:
      name: nginx
      state: reloaded
