---
# tasks file for initapps
- name: configuration
  become: true
  block:
  - name: config nginx
    copy:
      src: /home/user/task/info.php
      dest: /var/www/sites/joomla/info.php
  - name: config nginx
    copy:
      src: /home/user/task/joomla.conf
      dest: /etc/nginx/sites-available/joomla.conf
  - name: symlink
    ansible.builtin.file:
      src: /etc/nginx/sites-available/joomla.conf
      dest: /etc/nginx/sites-enabled/joomla.conf
      state: link
  - name: delete default
    ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  - name: Start and enable nginx service
    service:
      name: nginx
      state: reloaded

  - name: set root account
    become: true
    community.mysql.mysql_user:
      name: "{{ mysql_root }}"
      password:  "{{ mysql_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      check_implicit_admin: yes

  - name: set root account
    become: true
    community.mysql.mysql_user:
      name: "{{ mysql_user }}"
      password:  "{{ mysql_user_password }}"
      check_implicit_admin: yes
      login_user: "{{ mysql_root }}"
      login_password:  "{{ mysql_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present
