---
# tasks file for initapps
- name: Configuration
  become: true
  block:
    - name: Config nginx
      ansible.builtin.copy:
        src: /home/user/task/info.php
        dest: /var/www/sites/joomla/info.php
        owner: root
        group: root
        mode: '0644'
    - name: Config nginx
      ansible.builtin.copy:
        src: /home/user/task/joomla.conf
        dest: /etc/nginx/sites-available/joomla.conf
        owner: root
        group: root
        mode: '0644'        
    - name: Symlink
      ansible.builtin.file:
        src: /etc/nginx/sites-available/joomla.conf
        dest: /etc/nginx/sites-enabled/joomla.conf
        state: link
    - name: Delete default
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Start and enable nginx service
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Set root account
      become: true
      community.mysql.mysql_user:
        name: "{{ mysql_root }}"
        password: "{{ mysql_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: true

    - name: Create a new database with name 'joomla_db'
      community.mysql.mysql_db:
        name: joomla_db
        state: present
        login_user: "{{ mysql_root }}"
        login_password: "{{ mysql_password }}"
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Set admin account
      become: true
      community.mysql.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        check_implicit_admin: true
        login_user: "{{ mysql_root }}"
        login_password: "{{ mysql_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        priv: "*.*:ALL"
        state: present

    - name: Restart mysql
      ansible.builtin.service:
        name: mysql
        state: restarted
