- name: Install PHP on Debian based OS
  become: true
  block:
    - name: Install PHP
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: '{{ soft_php }}'
